const menu = [{item_name: 'Whole Bean', item_path: './menu/Whole Bean.jpg'},
{item_name: 'Iced Teas', item_path: './menu/Iced Teas.jpg'},
{item_name: 'Snacks & Sweets', item_path: './menu/Snacks & Sweets.jpg'},
{item_name: 'Bakery', item_path: './menu/Bakery.jpg'},
{item_name: 'Oatmeal & Yogurt', item_path: './menu/Oatmeal & Yogurt.jpg'},
{item_name: 'Cold Coffees', item_path: './menu/Cold Coffees.jpg'},
{item_name: 'Hot Breakfast', item_path: './menu/Hot Breakfast.jpg'},
{item_name: 'Hot Teas', item_path: './menu/Hot Teas.jpg'},
{item_name: 'Mugs', item_path: './menu/Mugs.jpg'},
{item_name: 'Other', item_path: './menu/Other.jpg'},
{item_name: 'VIA® Instant', item_path: './menu/VIA® Instant.jpg'},
{item_name: 'Cold Drinks', item_path: './menu/Cold Drinks.jpg'},
{item_name: 'Hot Drinks', item_path: './menu/Hot Drinks.jpg'},
{item_name: 'Tumblers', item_path: './menu/Tumblers.jpg'},
{item_name: 'Oleato™', item_path: './menu/Oleato™.jpg'},
{item_name: 'Hot Coffees', item_path: './menu/Hot Coffees.jpg'},
{item_name: 'Frappuccino® Blended Beverages', item_path: './menu/Frappuccino® Blended Beverages.jpg'},
{item_name: 'Lunch', item_path: './menu/Lunch.jpg'},
{item_name: 'Cold Cups', item_path: './menu/Cold Cups.jpg'}]